import queryServer from "..";

import { z } from "zod";
import { Options } from "@/Options";

const resultsSchema = z.object({
  latency: z.number()
    .int().nonnegative(),

  motd: z.string()
    .nonempty(),
  players: z.object({
    online: z.number()
      .int().nonnegative(),
    max: z.number()
      .int().nonnegative(),
    list: z.array(
      z.string().nonempty()
    ).optional()
  }).optional(),

  version: z.string().nonempty(),
  favicon: z.string().nonempty().optional(),

  type: z.union([
    z.literal("Unknown"),
    z.literal("Crossplay"),
    z.literal("Bedrock"),
    z.literal("Java")
  ]),

  ip: z.string().nonempty(),
  hostname: z.string().nonempty().optional(),

  debug: z.object({
    java: z.boolean().optional(),
    bedrock: z.boolean().optional(),
    query: z.boolean().optional(),

    srvs: z.array(
      z.string().nonempty()
    ).optional(),

    options: z.instanceof(Options)
  }),
});

describe("queryServer", () => {
  const TimeoutOpts = { timeout: 5_000 };

  it.concurrent.each<[string, Partial<Options>?]>([
    ["mslc.mc-complex.com"],
    ["mc.insanitycraft.net"],
    ["mcl.blossomcraft.org"],
    ["grmpixelmon.com"],
    ["msl.simplesurvival.gg"],
    ["mc.advancius.net"],
    ["mcsl.applecraft.org"],
    ["mcsl.dogecraft.net"],
    ["play.blockcraft.uk"],
    ["EC-MC.NET"],
    ["mcslm.pika.host"],
    ["play.penguin.gg"],
    ["play.neocubest.com"],
    ["akumamc.net"],
    ["msl.pixelmonrealms.com"],
    ["fun.opblocks.com"],
    ["mcslm.jartex.fun"],
    ["play.applemc.fun"],
    ["msl.pokehub.org"],
    ["play.fruitysmp.com"],
    ["ms.Minerival.org"],
    ["play.pokesaga.org"],
    ["mcsl.lemoncloud.net"],
    ["play.jackpotmc.com:57846"],
    ["play.vulengate.com"],
    ["msl.ultimis.net"],
    ["sl.minecadia.com"],
    ["play.underblock.gg"],
    ["play.mc-speed.com"],
    ["skyblock.net"],
    ["play.anubismc.com"],
    ["mcsl.oneblockmc.com"],
    ["mc.gamster.org"],
    ["fun.oplegends.com"],
    ["join.mccentral.org"],
    ["go.mineberry.org"],
    ["play.vanillaeuropa.com"],
    ["mcsl.gtm.network"],
    ["mcsl.vortexnetwork.net"],
    ["play.ecosmp.net"],
    ["fly.play-gamermine.online"],
    ["Herobrine.org"],
    ["mcsl.zedarmc.com"],
    ["theuniverse.network"],
    ["MC.CosmicMC.net"],
    ["msl.mc-blaze.com"],
    ["play.boxpvp.net"],
    ["minecraftonline.com"],
    ["mcsl.wildprison.net"],
    ["play.astrocraft.org"],
    ["play.cubecraft.net"],
    ["msl.minewind.net"],
    ["mc.mcs.gg"],
    ["play.omegaminecraft.com"],
    ["Play.Performium.co"],
    ["play.FarzySMP.com"],
    ["msl.ccnetmc.com"],
    ["mcsl.melonsmp.net"],
    ["LeoneMC.net"],
    ["armamc.com"],
    ["play.smphub.net"],
    ["sl.swancraftmc.com"],
    ["mc.lotc.co"],
    ["play.pocketpixels.net"],
    ["mc.safesurvival.net"],
    ["play.mineheart.net"],
    ["gengar.enchantmc.com"],
    ["pokecentral.org"],
    ["play.bumblecraft.net"],
    ["play.rulercraft.com"],
    ["imaginefun.net"],
    ["play.lilacmc.net"],
    ["mcsl.semisurvivalcraft.com"],
    ["mc.omegacraft.cl"],
    ["play.stealcadia.com"],
    ["127.0.0.1"],
    ["play.infinitycraftnet.com"],
    ["play.fallentech.io"],
    ["mc.hypixel.net"],
    ["play.lbsg.net"],
    ["us.mineplex.com"],
    ["pe.mineplex.com"],
    ["hub.mc-complex.com"],
    ["mchub.com"],
    ["play.pixelmonrealms.com"],
    ["DonutSMP.net"],
    ["play.EarthMC.net"],
    ["play.melonsmp.fun"],
    ["mc.applecraft.org"],
    ["play.tulipsurvival.com"],
    ["org.archonhq.net"],
    ["play.valatic.net"],
    ["Play.datblock.com"],
    ["minehut.com"],
    ["hub.opblocks.com"],
    ["geyser.pixelblockmc.com"],
    ["play.jartexnetwork.com"],
    ["lifestealmc.net"],
    ["kiwismp.fun"],
    ["buzz.cosmicsurvival.com"],
    ["play.blossomcraft.org"],
    ["br.craftyourtown.com"],
    ["buzz.playfuse.net"],
    ["play.vanillarealms.com"],
    ["buzz.lunarsmp.org"],
    ["buzz.catcraft.net"],
    ["play.huabacraft.com"],
    ["bedrock.advancius.net"],
    ["mc.thecavern.net"],
    ["mc.projects.gg"],
    ["play.kiwimc.com"],
    ["play.mc-ages.com"],
    ["kingdomsandruins.com"],
    ["play.maritime.gg"],
    ["play.static-studios.net"],
    ["play.infinitemc.net"],
    ["medieval-vanilla.com"],
    ["play.togethercraft.online"],
    ["mcsl.PlayFuse.net"],
    ["join.ventureland.net"],
    ["play.limitlessmc.net"],
    ["mc4.monsterfarmer.com"],
    ["play.emc.gs"],
    ["178.33.34.224"],
    ["mcsl.haycube.net"],
    ["pixelmon.projectshiba.com"],
    ["mc.pandacraft.cc"],
    ["mc.phoenixblazing.org"],
    ["play.alttd.com"],
    ["I-Pixelmon.com"],
    ["harrys.network"],
    ["Play.HappyCloudMC.com"],
    ["play.larteno.com"],
    ["msl.labs-mc.com"],
    ["Play.SiriusMC.net"],
    ["play.alathramc.com"],
    ["theogsmp.com"],
    ["rl.craftersland.net"],
    ["msl.serb-craft.com"],
    ["mc.pokeland.world"],
    ["sentouki.net"],
    ["cubeside.de"],
    ["mcsl.savermc.net"],
    ["play.creativefun.net"],
    ["mcsl.bosscraft.net"],
    ["massivecraft.com"],
    ["purityvanilla.com"],
    ["epic.newwindserver.com"],
    ["msl.oreo.gg"],
    ["play.wildercraft.net"],
    ["play.luckysb.org"],
    ["play.lokamc.com"],
    ["sky-mc.net"],
    ["trappedmc.com"],
    ["play.extremecraft.net"],
    ["DankPrison.com"],
    ["mcsl.cloudsurvival.net"],
    ["play.craftmania.ro"],
    ["play.FlareMC.org"],
    ["mc.queercraft.net"],
    ["play.squirtlesquadmc.com"],
    ["smp.hometownmc.com"],
    ["Vanilla.myftb.de"],
    ["noob-friendly.com"],
    ["play.ve-mc.com"],
    ["Shatteredvanilla.net"],
    ["mcsl.crankedmc.com"],
    ["msl.immortalrealms.gg"],
    ["play.minecove.org"],
    ["play.royale-mc.com"],
    ["play.peacefulfarms.net"],
    ["themcx.com"],
    ["game.mineraze.net"],
    ["play.apollonetwork.us"],
    ["msl.thenestsmp.com"],
    ["play.noblerealms.com"],
    ["ml.mineglobe.org"],
    ["minecraft.spyninjas.net"],
    ["nordmc.net"],
    ["hub.megacrafting.com"],
    ["server.playmonumenta.com"],
    ["jogar.absolutgg.com.br"],
    ["play.yomnetwork.ca"],
    ["marscraft.org"],
    ["boatsnbunnies.com"],
    ["play.hearthcraft.net"],
    ["play.guildcraft.net"],
    ["play.smpearth.com"],
    ["play.pixelpunchers.net"],
    ["91.109.116.17"],
    ["mc.xironite.org"],
    ["play.primegames.net"],
    ["Play.FoxMC.Net"],
    ["play.mc-oasis.com"],
    ["atm8.moddedmc.net"],
    ["play.jozmc.com"],
    ["play.goldenleafmc.com"],
    ["play.flightsmp.com"],
    ["mcsl.AspiriaMc.Com"],
    ["pvpwars.net"],
    ["play.envyblock.com"],
    ["terona.org"],
    ["mcsl.havencraftmc.com"],
    ["play.hallowedfantasy.com"],
    ["mc.classicsurvival.net"],
    ["mc.gamersreact.net"],
    ["play.mcarcadia.com"],
    ["Elgae.net"],
    ["play.chasecraft.gg"],
    ["gsgserver.com.br"],
    ["play.strongcraft.org"],
    ["play.rexkraft.com"],
    ["mcsl.ecc.eco"],
    ["Luxcube.net"],
    ["msl.fablesmp.com"],
    ["mcsl.pixelblockmc.com"],
    ["tekkit2.craftersland.net"],
    ["the-farm.network"],
    ["server.pixelmoncraft.com"],
    ["play.democracycraft.net"],
    ["smp.vanillavista.net"],
    ["minerefuge.com"],
    ["inf.craftersland.net"],
    ["play.bennixmc.com"],
    ["play.RustCraftMC.com"],
    ["riftmc.org"],
    ["server.elementanimation.com"],
    ["HexagonMC.eu"],
    ["spil.sufosmc.dk"],
    ["cherryblossom.apexmc.co"],
    ["play.minesea.net"],
    ["mcsl.flicked.net"],
    ["mc.cwresports.lk"],
    ["play.blocksmc.com"],
    ["play.astridcloud.xyz"],
    ["play.vanillatyme.com"],
    ["MOOHUB.NET"],
    ["wintermc.net"],
    ["evolvesmp.tk"],
    ["mc.riftland.com"],
    ["mc.leftypvp.net"],
    ["pixelmon-au.com"],
    ["mcvanilla.net"],
    ["msl.archermc.net"],
    ["play.acornmc.org"],
    ["play.townysmp.com"],
    ["play.prismacraft.net"],
    ["mc.vanillahigh.net"],
    ["play.robblestone.com"],
    ["play.theloftmc.com"],
    ["mc.c-bd.org"],
    ["play.vestriamc.com"],
    ["play.exeoscraft.com"],
    ["play.simplyvanilla.co"],
    ["KingSMP.net"],
    ["survivalmp.ga"],
    ["www.leki-world.de"],
    ["vote.pitsim.net"],
    ["play.lifestealhybrid.com"],
    ["play.vanillagames.net"],
    ["play.projectazoth.net"],
    ["play.boxxymc.fun"],
    ["mc.thealater.com"],
    ["mc.alpinesmc.com"],
    ["siphonmc.com"],
    ["play.spongecraft.net"],
    ["play.pokeparadise.org"],
    ["superpixelserver.com"],
    ["next.mym.li"],
    ["bmc1.moddedmc.net"],
    ["hub.reforgednetwork.com"],
    ["play.skykingdoms.net"],
    ["mc.peacefulvanilla.club"],
    ["pokeresort.com"],
    ["54.39.196.69:25590"],
    ["mc.differentcraft.net"],
    ["play.stormylagoon.com"],
    ["mineverse.com"],
    ["play.civmc.net"],
    ["jogar.austv.net"],
    ["play.townyeternal.com"],
    ["play.pixelgaming.co"],
    ["minecraftbrasil.com"],
    ["play.zenuscraft.com:25604"],
    ["play.lgbtempire.net"],
    ["play.nolifesquad.com"],
    ["v8c.net"],
    ["play.dexmasters.net"],
    ["aztecmc.org"],
    ["spela.mucraft.se"],
    ["vip.mcers.es"],
    ["play.woodgaming.live"],
    ["mc.minefall.eu"],
    ["minevane.nz"],
    ["play.mcbusinesscraft.com"],
    ["play.thebruhclub.com"],
    ["mc.cookiesandcreamhype.com"],
    ["play.trinitymc.org"],
    ["play.shantycraft.com"],
    ["mc.warofeitr.com"],
    ["play.cubedao.net"],
    ["play.InfuseSMP.com"],
    ["play.toxigon.com"],
    ["gt.craftersland.net"],
    ["play.justminecraft.nl"]
  ])("runs without failure for %p", async (host, opts) => {
    const results = await queryServer(host, { ...TimeoutOpts, ...opts })

    results.favicon &&= `(${results.favicon.length} bytes...)`;

    expect(() => {
      resultsSchema.parse(results)
    }).not.toThrow();
  }, 10_000);
});
